type Category {
  label: String!
  value: Int!
}

type CategoryList {
  itemList: [Category!]!
  totalCount: Int!
}

input CreatePostInput {
  categoryNo: Int!
  contents: String!
  title: String!
}

scalar DateTime

input DeletePostInput {
  categoryNo: Int!
  postNo: Int!
}

type Mutation {
  createPost(input: CreatePostInput!): PostUpsertResult!
  deletePost(input: DeletePostInput!): Boolean!
  sendPushToAll(input: SendPushToAllInput!): Boolean!
  subscribeWebPush(input: SubscribeWebPushInput!): Boolean!
  unsubscribeWebPush(input: UnsubscribeWebPushInput!): Boolean!
  updatePost(input: UpdatePostInput!): PostUpsertResult!
}

type Post {
  categoryLabel: String!
  categoryNo: Int!
  content: String
  createdAt: DateTime!
  postNo: Int!
  title: String!
  writer: Writer!
}

type PostList {
  itemList: [PostSummary!]!
  totalCount: Int!
}

type PostSummary {
  author: String
  categoryLabel: String!
  categoryNo: Int!
  createdAt: DateTime!
  postNo: Int!
  subDescription: String
  title: String!
}

type PostUpsertResult {
  categoryNo: Int!
  postNo: Int!
}

type Query {
  categoryList: CategoryList!
  getRecentPostList(limitCount: Int): PostList!
  post(categoryNo: Int!, postNo: Int!): Post
  postList(categoryId: Int): PostList!
  user(id: ID!): User
}

input SendPushToAllInput {
  content: String!
  title: String!
  url: String!
}

input SubscribeWebPushInput {
  auth: String!
  endPoint: String!
  key: String!
}

input UnsubscribeWebPushInput {
  key: String!
}

input UpdatePostInput {
  categoryNo: Int!
  contents: String!
  id: Int!
  title: String!
}

type User {
  id: ID!
  userId: String!
  userName: String!
}

type Writer {
  imageUrl: String!
  nickName: String
  no: Int!
}