input CompleteTodoInput {
  id: String!
  isCompleted: Boolean!
}

input CreateTodoCategoryInput {
  name: String!
}

input CreateTodoInput {
  categoryId: String
  dueDate: String
  priority: TodoPriority
  title: String!
}

scalar DateTime

input DeleteTodoCategoryInput {
  id: String!
}

input DeleteTodoInput {
  id: String!
}

type IdMapping {
  from: String!
  to: String!
}

input ImportTodoCategoryInput {
  clientId: String!
  createdAt: DateTime
  name: String!
  order: Int!
}

input ImportTodoInput {
  categoryClientId: String
  clientId: String!
  completedAt: DateTime
  createdAt: DateTime
  deletedAt: DateTime
  dueDate: String
  isCompleted: Boolean!
  memo: String!
  order: Int!
  priority: TodoPriority!
  title: String!
  updatedAt: DateTime
}

input ImportTodoListInput {
  categoryList: [ImportTodoCategoryInput!]!
  itemList: [ImportTodoInput!]!
}

type Mutation {
  completeTodo(input: CompleteTodoInput!): Todo!
  createTodo(input: CreateTodoInput!): Todo!
  createTodoCategory(input: CreateTodoCategoryInput!): TodoCategory!
  deleteTodo(input: DeleteTodoInput!): Boolean!
  deleteTodoCategory(input: DeleteTodoCategoryInput!): Boolean!
  emptyTrash: Boolean!
  importTodoList(input: ImportTodoListInput!): TodoImportResult!
  restoreTodo(input: RestoreTodoInput!): Todo!
  trashTodo(input: TrashTodoInput!): Todo!
  updateTodo(input: UpdateTodoInput!): Todo!
  updateTodoCategory(input: UpdateTodoCategoryInput!): TodoCategory!
}

type Query {
  todoCategoryList: TodoCategoryList!
  todoList: TodoList!
}

input RestoreTodoInput {
  id: String!
}

type Todo {
  categoryId: String
  completedAt: DateTime
  createdAt: DateTime!
  deletedAt: DateTime
  dueDate: String
  id: String!
  isCompleted: Boolean!
  memo: String!
  order: Int!
  priority: TodoPriority!
  title: String!
  updatedAt: DateTime!
}

type TodoCategory {
  createdAt: DateTime!
  id: String!
  name: String!
  order: Int!
}

type TodoCategoryList {
  itemList: [TodoCategory!]!
  totalCount: Int!
}

type TodoImportResult {
  categoryIdMap: [IdMapping!]!
  todoIdMap: [IdMapping!]!
}

type TodoList {
  itemList: [Todo!]!
  totalCount: Int!
}

enum TodoPriority {
  HIGH
  LOW
  MEDIUM
  NONE
}

input TrashTodoInput {
  id: String!
}

input UpdateTodoCategoryInput {
  id: String!
  name: String!
}

input UpdateTodoInput {
  categoryId: String
  dueDate: String
  id: String!
  memo: String
  priority: TodoPriority
  title: String
}