input AddArticleToCurationInput {
  articleId: String!
  weekKey: String!
}

type Article {
  categoryId: String!
  createdAt: DateTime!
  id: String!
  seo: ArticleSeo
  title: String!
  updatedAt: DateTime!
  url: String!
}

type ArticleCategory {
  createdAt: DateTime!
  id: String!
  name: String!
  order: Int!
}

type ArticleCategoryList {
  itemList: [ArticleCategory!]!
  totalCount: Int!
}

type ArticleIdMapping {
  from: String!
  to: String!
}

type ArticleImportResult {
  articleIdMap: [ArticleIdMapping!]!
  categoryIdMap: [ArticleIdMapping!]!
}

type ArticleList {
  itemList: [Article!]!
  totalCount: Int!
}

type ArticleSeo {
  description: String
  imageUrl: String
  title: String
}

input ArticleSeoInput {
  description: String
  imageUrl: String
  title: String
}

input CreateArticleCategoryInput {
  name: String!
}

input CreateArticleInput {
  categoryId: String!
  seo: ArticleSeoInput
  title: String!
  url: String!
}

scalar DateTime

input DeleteArticleCategoryInput {
  id: String!
}

input DeleteArticleInput {
  id: String!
}

input ImportArticleCategoryInput {
  clientId: String!
  createdAt: DateTime
  name: String!
  order: Int!
}

input ImportArticleInput {
  categoryClientId: String!
  clientId: String!
  createdAt: DateTime
  seo: ArticleSeoInput
  title: String!
  updatedAt: DateTime
  url: String!
}

input ImportArticleListInput {
  categoryList: [ImportArticleCategoryInput!]!
  curationList: [ImportCurationInput!]!
  itemList: [ImportArticleInput!]!
}

input ImportCurationInput {
  articleClientIds: [String!]!
  weekKey: String!
}

type Mutation {
  addArticleToCuration(input: AddArticleToCurationInput!): WeeklyCuration!
  createArticle(input: CreateArticleInput!): Article!
  createArticleCategory(input: CreateArticleCategoryInput!): ArticleCategory!
  deleteArticle(input: DeleteArticleInput!): Boolean!
  deleteArticleCategory(input: DeleteArticleCategoryInput!): Boolean!
  importArticleList(input: ImportArticleListInput!): ArticleImportResult!
  removeArticleFromCuration(input: RemoveArticleFromCurationInput!): WeeklyCuration!
  updateArticle(input: UpdateArticleInput!): Article!
  updateArticleCategory(input: UpdateArticleCategoryInput!): ArticleCategory!
}

type Query {
  articleCategoryList: ArticleCategoryList!
  articleList(categoryId: String): ArticleList!
  weeklyCurationList: WeeklyCurationList!
}

input RemoveArticleFromCurationInput {
  articleId: String!
  weekKey: String!
}

input UpdateArticleCategoryInput {
  id: String!
  name: String!
}

input UpdateArticleInput {
  categoryId: String
  id: String!
  seo: ArticleSeoInput
  title: String
  url: String
}

type WeeklyCuration {
  articleIds: [String!]!
  articles: [Article!]!
  weekKey: String!
}

type WeeklyCurationList {
  itemList: [WeeklyCuration!]!
  totalCount: Int!
}