type AuthTokens {
  accessToken: String!
  refreshToken: String!
}

input CheckRefreshTokenInput {
  refreshToken: String!
}

type CheckTokenResult {
  authTokens: AuthTokens!
  userInfo: UserInfo!
}

scalar DateTime

input LoginByShareCodeInput {
  shareCode: String!
}

input LoginBySocialInput {
  email: String
  imageUrl: String!
  loginType: SocialLoginType!
  name: String
  socialId: String!
}

type LoginResult {
  accessToken: String!
  refreshToken: String!
  user: UserInfo!
}

type Mutation {
  checkRefreshToken(input: CheckRefreshTokenInput!): AuthTokens!
  loginByShareCode(input: LoginByShareCodeInput!): LoginResult!
  loginBySocial(input: LoginBySocialInput!): LoginResult!
  logout: Boolean!
  upsertShareCode: String!
}

type Query {
  checkAccess: Int!
  checkToken: CheckTokenResult!
  getShareCode: String!
  me: UserInfo!
}

enum SocialLoginType {
  FACEBOOK
  GOOGLE
  KAKAO_TALK
}

type UserInfo {
  authType: String
  createdAt: DateTime!
  email: String!
  id: Int!
  loginType: String!
  name: String!
  profileImg: String!
  socialId: String!
  updatedAt: DateTime!
}