type Mutation
scalar DateTime

type Category {
  value: Int!
  label: String!
}

type CategoryList {
  totalCount: Int!
  itemList: [Category!]!
}

type Writer {
  no: Int!
  nickName: String
  imageUrl: String!
}

type PostSummary {
  postNo: Int!
  title: String!
  subDescription: String
  categoryLabel: String!
  categoryNo: Int!
  createdAt: DateTime!
  author: String
}

type PostList {
  totalCount: Int!
  itemList: [PostSummary!]!
}

type Post {
  postNo: Int!
  title: String!
  content: String
  categoryLabel: String!
  categoryNo: Int!
  createdAt: DateTime!
  writer: Writer!
}

type PostUpsertResult {
  postNo: Int!
  categoryNo: Int!
}

input CreatePostInput {
  categoryNo: Int!
  title: String!
  contents: String!
}

input UpdatePostInput {
  id: Int!
  categoryNo: Int!
  title: String!
  contents: String!
}

input DeletePostInput {
  categoryNo: Int!
  postNo: Int!
}

extend type Query {
  categoryList: CategoryList!
  postList(categoryId: Int): PostList!
  getRecentPostList(limitCount: Int): PostList!
  post(categoryNo: Int!, postNo: Int!): Post
}

extend type Mutation {
  createPost(input: CreatePostInput!): PostUpsertResult!
  updatePost(input: UpdatePostInput!): PostUpsertResult!
  deletePost(input: DeletePostInput!): Boolean!
}
