type Query
type Mutation
scalar DateTime

extend type Mutation {
  createAccountBookCategory(input: CreateAccountBookCategoryInput!): AccountBookCategory!
  deleteAccountBookCategory(input: DeleteAccountBookCategoryInput!): Boolean!
  createAccountBook(input: CreateAccountBookInput!): AccountBook!
  updateAccountBook(input: UpdateAccountBookInput!): AccountBook!
  deleteAccountBook(input: DeleteAccountBookInput!): Boolean!
  createAccount(input: CreateAccountInput!): Account!
  completeAccountExpiration(input: CompleteAccountExpirationInput!): Boolean!
  deleteAccount(input: DeleteAccountInput!): Boolean!
  createDeposit(input: CreateDepositInput!): Deposit!
  createBucketList(input: CreateBucketListInput!): BucketList!
  updateBucketList(input: UpdateBucketListInput!): BucketList!
  completeBucketList(input: CompleteBucketListInput!): Boolean!
  deleteBucketList(input: DeleteBucketListInput!): Boolean!
  createBucketListTodo(input: CreateBucketListTodoInput!): BucketListTodo!
  updateBucketListTodoComplete(input: UpdateBucketListTodoCompleteInput!): BucketListTodo!
  deleteBucketListTodo(input: DeleteBucketListTodoInput!): Boolean!
  createRegularExpenditure(input: CreateRegularExpenditureInput!): RegularExpenditure!
  deleteRegularExpenditure(input: DeleteRegularExpenditureInput!): Boolean!
}

extend type Query {
  account(id: ID!): Account
  accountList(limitCount: Int): AccountList!
  getAccountLastUpdatedDate: DateTime!
  mainInfo: MainInfo!
  bucketListSummaryList(limitCount: Int): BucketListSummaryList!
  bucketList(id: ID!): BucketList
  getBucketListLastUpdatedDate: DateTime!
  getBucketListItemLastUpdatedDate(id: ID!): DateTime!
  accountBookList(dateTime: DateTime!): AccountBookList!
  accountBook(id: ID!): AccountBook
  accountBookCategoryImageList: AccountBookCategoryImageList!
  accountBookCategoryList: AccountBookCategoryList!
  getAccountBookStatisticList(startDate: DateTime!, endDate: DateTime!, type: AccountBookCategoryType!): StatisticList!
  regularExpenditureGroupList(limitCount: Int): RegularExpenditureGroupList!
  #    users: [User!]!
  #    user(id: ID!): User
  #    userShareCodes: [UserShareCode!]!
  #    userShareCode(id: ID!): UserShareCode
  #    savingTypes: [SavingType!]!
  #    savingType(id: ID!): SavingType
  #    accounts: [Account!]!
  #    account(id: ID!): Account
  #    accountBooks: [AccountBook!]!
  #    accountBook(id: ID!): AccountBook
  #    accountBookCategories: [AccountBookCategory!]!
  #    accountBookCategory(id: ID!): AccountBookCategory
  #    deposits: [Deposit!]!
  #    deposit(id: ID!): Deposit
  #    accountBookCategoryImages: [AccountBookCategoryImage!]!
  #    accountBookCategoryImage(id: ID!): AccountBookCategoryImage
  #    bucketLists: [BucketList!]!
  #    bucketList(id: ID!): BucketList
  #    regularExpenditures: [RegularExpenditure!]!
  #    regularExpenditure(id: ID!): RegularExpenditure
  #    todos: [Todo!]!
  #    todo(id: ID!): Todo
}

input CreateAccountBookCategoryInput {
  name: String!
  type: AccountBookCategoryType!
  useStatistic: Boolean!
  accountBookCategoryImageId: Int!
}

input DeleteAccountBookCategoryInput {
  id: ID!
}

input CreateAccountBookInput {
  title: String!
  amount: Int!
  memo: String
  type: AccountBookCategoryType!
  registerDateTime: DateTime!
  categoryId: Int!
  isDisabledBudget: Boolean
  scheduledPaymentType: ScheduledPaymentType
  scheduledPaymentDay: Int
  installmentMonth: Int
}

input UpdateAccountBookInput {
  id: ID!
  title: String
  amount: Int
  memo: String
  type: AccountBookCategoryType
  registerDateTime: DateTime
  categoryId: Int
  isDisabledBudget: Boolean
}

input DeleteAccountBookInput {
  id: ID!
}

input CreateAccountInput {
  title: String!
  taxType: String!
  regularTransferDate: Int!
  rate: Float!
  startDate: DateTime!
  endDate: DateTime!
  amount: Int!
  savingTypeId: Int!
}

input CompleteAccountExpirationInput {
  id: ID!
}

input DeleteAccountInput {
  id: ID!
}

input CreateDepositInput {
  accountId: Int!
  amount: Int!
  depositDate: DateTime
}

input CreateBucketListInput {
  title: String!
  description: String!
  completeDate: DateTime!
  imageUrl: String
  thumbImageUrl: String
  todoList: [BucketListTodoInput!]
}

input UpdateBucketListInput {
  id: ID!
  title: String!
  description: String!
  completeDate: DateTime!
  imageUrl: String
  thumbImageUrl: String
}

input CompleteBucketListInput {
  id: ID!
}

input DeleteBucketListInput {
  id: ID!
}

input CreateBucketListTodoInput {
  bucketListId: Int!
  title: String!
  isComplete: Boolean!
}

input UpdateBucketListTodoCompleteInput {
  todoId: ID!
  isComplete: Boolean!
}

input DeleteBucketListTodoInput {
  todoId: ID!
}

input CreateRegularExpenditureInput {
  title: String!
  amount: Int!
  regularDate: Int!
  isAutoExpenditure: Boolean!
  categoryId: Int!
}

input DeleteRegularExpenditureInput {
  id: ID!
}

type AccountList {
  totalCount: Int!
  itemList: [Account!]!
}

type AccountBookList {
  totalCount: Int!
  itemList: [AccountBook!]!
}

type AccountBookCategoryList {
  totalCount: Int!
  itemList: [AccountBookCategory!]!
}

type AccountBookCategoryImageList {
  totalCount: Int!
  itemList: [AccountBookCategoryImage!]!
}

type BucketListSummaryList {
  totalCount: Int!
  itemList: [BucketListSummary!]!
}

type StatisticList {
  totalCount: Int!
  itemList: [Statistic!]!
}

type RegularExpenditureGroupList {
  totalCount: Int!
  itemList: [RegularExpenditureGroup!]!
}

type Statistic {
  amount: Int!
  percentage: Float!
  useStatistic: Boolean!
  categoryName: String!
  categoryId: String!
  list: [StatisticItem!]!
}

type StatisticItem {
  title: String!
  amount: Int!
  registerDateTime: DateTime!
}

enum ScheduledPaymentType {
  REPEAT
  INSTALLMENT
}

type MainInfo {
  totalSavedAmount: Int!
  totalSavedAmountExceptCurrentMonth: Int!
  accounts: [Account!]!
  bucketList: [BucketListSummary!]!
}

type BucketListSummary {
  id: ID!
  title: String!
  isComplete: Boolean!
  completeDate: DateTime!
  todoCount: Int!
  completeTodoCount: Int!
  thumbImageUrl: String!
  updatedAt: DateTime!
}

input BucketListTodoInput {
  title: String!
  isComplete: Boolean!
}

type WoolBankUser {
  id: ID!
  name: String!
  email: String!
  loginType: String!
  socialId: String!
  profileImg: String!
  accounts: [Account!]!
  bucketLists: [BucketList!]!
  deposits: [Deposit!]!
  todos: [BucketListTodo!]!
  accountBooks: [AccountBook!]!
  accountBookCategories: [AccountBookCategory!]!
  accountBookCategoryImages: [AccountBookCategoryImage!]!
  regularExpenditures: [RegularExpenditure!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type UserShareCode {
  id: ID!
  userId: Int!
  shareCode: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type SavingType {
  id: ID!
  name: String!
  type: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Account {
  id: ID!
  taxType: String!
  regularTransferDate: Int!
  rate: Float!
  title: String!
  amount: Int!
  currentAmount: Int!
  userId: Int!
  isExpiration: Boolean!
  startDate: DateTime!
  endDate: DateTime!
  savingTypeId: Int!
  savingType: SavingType!
  deposits: [Deposit!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type AccountBook {
  id: ID!
  title: String!
  amount: Int!
  memo: String!
  type: AccountBookCategoryType!
  isRegularExpenditure: Boolean!
  isDisabledBudget: Boolean!
  regularDate: Int
  installmentMonth: Int
  paidInstallmentMonth: Int
  registerDateTime: DateTime!
  userId: Int!
  accountBookCategoryId: Int!
  accountBookCategory: AccountBookCategory!
  createdAt: DateTime!
  updatedAt: DateTime!
}

enum AccountBookCategoryType {
  EXPENDITURE
  INCOME
}

type AccountBookCategory {
  id: ID!
  name: String!
  delYn: Boolean!
  type: AccountBookCategoryType!
  useStatistic: Boolean!
  userId: Int!
  accountBookCategoryImageId: Int!
  accountBookCategoryImage: AccountBookCategoryImage!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Deposit {
  id: ID!
  amount: Int!
  prevTotalAmount: Int!
  userId: Int!
  accountId: Int!
  account: Account
  depositDate: DateTime!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type AccountBookCategoryImage {
  id: ID!
  name: String!
  imageUrl: String!
  userId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type BucketList {
  id: ID!
  isComplete: Boolean!
  title: String!
  description: String!
  userId: Int!
  user: WoolBankUser
  todoList: [BucketListTodo!]!
  completeDate: DateTime!
  imageUrl: String!
  thumbImageUrl: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type RegularExpenditureGroup {
  type: AccountBookCategoryType!
  name: String!
  imageUrl: String!
  list: [CustomRegularExpenditure!]!
}

type CustomRegularExpenditure {
  id: ID!
  title: String!
  amount: Int!
  regularDate: Int!
  isAutoExpenditure: Boolean!
  userId: Int!
  accountBookCategoryId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  accountBookCategory: AccountBookCategory!
  regularExpenditureDay: DateTime!
}

type RegularExpenditure {
  id: ID!
  title: String!
  amount: Int!
  regularDate: Int!
  isAutoExpenditure: Boolean!
  userId: Int!
  accountBookCategoryId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  accountBookCategory: AccountBookCategory!
}

type BucketListTodo {
  id: ID!
  isComplete: Boolean!
  userId: Int!
  user: WoolBankUser
  title: String!
  bucketListId: Int!
  bucketList: BucketList
  createdAt: DateTime!
  updatedAt: DateTime!
}
