scalar DateTime

input DeleteMemoInput {
  id: String!
}

input ImportMemoInput {
  clientId: String!
  content: JSON!
  createdAt: DateTime
  title: String!
  updatedAt: DateTime
}

input ImportMemoListInput {
  itemList: [ImportMemoInput!]!
}

scalar JSON

type Memo {
  content: JSON!
  createdAt: DateTime!
  id: String!
  title: String!
  updatedAt: DateTime!
}

type MemoIdMapping {
  from: String!
  to: String!
}

type MemoImportResult {
  memoIdMap: [MemoIdMapping!]!
}

type MemoList {
  itemList: [MemoSummary!]!
  totalCount: Int!
}

type MemoSummary {
  createdAt: DateTime!
  id: String!
  title: String!
  updatedAt: DateTime!
}

type Mutation {
  createMemo: Memo!
  deleteMemo(input: DeleteMemoInput!): Boolean!
  importMemoList(input: ImportMemoListInput!): MemoImportResult!
  updateMemo(input: UpdateMemoInput!): Memo!
}

type Query {
  memo(id: String!): Memo
  memoList: MemoList!
}

input UpdateMemoInput {
  content: JSON
  id: String!
  title: String
}